name: UEPluginManager
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - expat=2.7.3=h885b0b7_4
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.3=pyhc872135_0
  - python=3.11.14=h981015d_0
  - setuptools=80.9.0=py311haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py311haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - altgraph==0.17.5
      - packaging==25.0
      - pefile==2024.8.26
      - platformdirs==4.5.1
      - pyinstaller==6.17.0
      - pyinstaller-hooks-contrib==2025.11
      - pyside6==6.10.1
      - pyside6-addons==6.10.1
      - pyside6-essentials==6.10.1
      - pywin32-ctypes==0.2.3
      - shiboken6==6.10.1
prefix: C:\Users\mengzhishanghun\miniconda3\envs\UEPluginManager
